version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.4.1
    ports:
      - "16349:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.4.1
    volumes:
      - /var/log/node:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki
