server:
    http_listen_port: 9080
    grpc_listen_port: 0
    log_level: "debug"
  
positions:
    filename: /tmp/positions.yaml
  
clients:
    - url: http://loki-gateway:80/loki/api/v1/push
  
scrape_configs:
  - job_name: system
    static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        __path__: /var/log/*log

  - job_name: testlogs
    static_configs:
    - targets:
        - localhost
      labels:
        job: testlogs
        __path__: /var/log3/*log

#  - job_name: journal
#    journal:
#      json: false
#      max_age: 12h
#      path: /var/log/journal
#      labels:
#        job: systemd-journal
#    relabel_configs:
#      - source_labels: ['__journal__systemd_unit']
#        target_label: 'unit'